POST {{url}}/role
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZmlyc3ROYW1lIjoiSm9uYXRob24iLCJsYXN0TmFtZSI6IkhpbGxsIiwiZW1haWwiOiJYWXc5M3ZUeXNPbjBxWXlId0BNcEN3LmRlIiwiaGFzRGFzaGJvYXJkQWNjZXNzIjp0cnVlLCJjcmVhdGVkQXQiOiIyMDI1LTA2LTEyVDIwOjI2OjMxLjU4NVoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA2LTEyVDIwOjI2OjMxLjU4NVoiLCJpYXQiOjE3NTAwMTk5MTEsImV4cCI6MTc1MDEwNjMxMX0.XK_HCoUJwcChNPMhXpsv_6YaFJ1tLDQiVxauyOf6kaA

{
  "name": "{{$random.address.city}}",
  "description": "description"
}

###
