GET {{url}}/user/me
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZmlyc3ROYW1lIjoiSm9uYXRob24iLCJsYXN0TmFtZSI6IkhpbGxsIiwiZW1haWwiOiJYWXc5M3ZUeXNPbjBxWXlId0BNcEN3LmRlIiwiaGFzRGFzaGJvYXJkQWNjZXNzIjpmYWxzZSwiY3JlYXRlZEF0IjoiMjAyNS0wNi0xMlQyMDoyNjozMS41ODVaIiwidXBkYXRlZEF0IjoiMjAyNS0wNi0xMlQyMDoyNjozMS41ODVaIiwiaWF0IjoxNzQ5ODAyNTIzLCJleHAiOjE3NDk4ODg5MjN9.LPcRPRVa42KfBrNLPTYlo25ZOWNVLTgjOCADI3cRG5o


###
